### ISSUE TITLE
Overclocking

### ISSUE THREAD

**Issue by MrPlusGH** [MrPlusGH/NPlusMiner-Documentation#1]
Thanks you @Tesla74 !
I did a couple edits.
I think we're good to go with a bit of formatting.

**Comment by Tesla74** [comment]
Looks good.  When using NvidiaInspector, does that override other overclocking software or should the other overclocking software be turned off?

**Comment by Tesla74** [comment]
I started to add to the Wiki, but going to have to learn how to format.  I'll work on it later tonight.

**Comment by Tesla74** [comment]
I like the md files.  It looks really nice with the formatting.  I'll try and learn that also and convert the text file to md.

**Comment by Tesla74** [comment]
Sorry for all the commits.. Learning this markdown :-)  Added page to Wiki.  You might want to check it over again as I made some changes.

**Comment by Tesla74** [comment]
I noticed in your example code you refer nvidiaInspector.exe.  I think that the latest version has been renamed nvidiaProfileInspector.exe.  This is the version that I linked in the document.  Can you check to see if it is okay?  Thanks.

**Comment by MrPlusGH** [comment]
nvidiaProfileInspector is used to modify profiles. nvidiaInspector modifies OC settings.

**Comment by Tesla74** [comment]
Thanks.  Do you have a download link for nvidiaInspector?  I don't see the original source.
This link says nvidiaInspector and nvidiaProfileInspecor are the same?
"NVIDIA Inspector, now also known as nvidiaProfileInspector"
http://www.guru3d.com/files-details/nvidia-inspector-download.html

**Comment by MrPlusGH** [comment]
Yep, looks like the correct link.

**Comment by MrPlusGH** [comment]
Done.
Will be updated if required in MD source file in Wiki.

Thank you @Tesla74 !!

**Comment by Tesla74** [comment]
Okay, I've updated links!
