### ISSUE TITLE
error in  Equihash

### ISSUE THREAD

**Issue by pinkzebrus** [MrPlusGH/NPlusMiner-Documentation#4]
Bminer          Equihash    269,76 KH/s   56,693 0,05669 26 731,754   210,16390 zergpoolplus-

[INFO] [2018-07-21T23:41:34+05:00] Total 2696.76 Sol/s 1440.83 Nonce/s Accepted shares 28 Rejected shares 0

**Comment by MrPlusGH** [comment]
Wrong repository, please open in MPlusMiner reporitory.
