### ISSUE TITLE
mine only when idle

### ISSUE THREAD

**Issue by MitchCarroll** [MrPlusGH/NPlusMiner-Documentation#8]
The "mine only when idle" config option is not explained in the documentation, and is not entirely self-explanatory. Does it mine only when the NPlusMiner application itself isn't being interacted with, or will it pause mining if, say, I start playing a game?

**Comment by MrPlusGH** [comment]
It mines only when there is no interaction in the session. If users do nothing like mowing mouse for the set period of time it will start mining. If user interacts again, it will stop mining.
Take it as "mine when I don't use my computer".
